open module com.mastfrog.generic.web.api {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.webapi;
    exports com.mastfrog.webapi.builtin;
    requires transitive com.mastfrog.acteur;
    requires transitive com.mastfrog.giulius;
    requires transitive com.mastfrog.giulius.tests;
    requires transitive com.mastfrog.netty.http.client;
    requires transitive com.mastfrog.scopes;
    requires java.desktop;
    requires java.logging;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

}
