// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.generic.web.api {
    exports com.mastfrog.webapi;
    exports com.mastfrog.webapi.builtin;

    // Sibling com.mastfrog/giulius-3.0.0-dev

    // Transitive detected by source scan
    requires com.mastfrog.giulius;

    // Sibling com.mastfrog/netty-http-client-3.0.0-dev
    requires com.mastfrog.netty.http.client;

    // Inferred from source scan
    requires com.mastfrog.preconditions;

    // Sibling com.mastfrog/scopes-3.0.0-dev
    requires com.mastfrog.scopes;

    // Inferred from source scan
    requires com.mastfrog.time;

    // Inferred from source scan

    // Transitive detected by source scan
    requires com.mastfrog.util.function;
    requires java.desktop;
    requires java.logging;

    // Inferred from test-source-scan
    requires transitive junit;

}
